---
- name: Include "{{ansible_os_family}}" tasks
  include: "{{ansible_os_family}}.yaml"

- name: Copy 'is_cluster_ready' file
  copy: dest=/bin/is_cluster_ready src=is_cluster_ready mode=0755 force=no

- lineinfile: dest=/etc/condor/condor_config regexp=REQUIRE_LOCAL_CONFIG_FILE line="REQUIRE_LOCAL_CONFIG_FILE=TRUE"
  notify: restart htcondor

- copy:
    content: |
       CONDOR_HOST = htcondoreserver
       BIND_ALL_INTERFACES = FALSE
       NETWORK_INTERFACE = {{ansible_default_ipv4.address}}
       ALLOW_WRITE = htcondoreserver, {{htcondor_vnode_prefix}}*.localdomain
       DAEMON_LIST = MASTER, COLLECTOR, NEGOTIATOR, SCHEDD
       NEGOTIATOR_INTERVAL = 30
       NEGOTIATE_ALL_JOBS_IN_CLUSTER = True
    dest: "/etc/condor/condor_config.local"
  notify: restart htcondor

- service: name=condor state=started
